// <auto-generated />
using System;
using CORE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CORE.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CORE.DOMAIN.Entities.EventoCivilizacional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ImpactoComida")
                        .HasColumnType("integer");

                    b.Property<int>("ImpactoMadeira")
                        .HasColumnType("integer");

                    b.Property<int>("ImpactoMoral")
                        .HasColumnType("integer");

                    b.Property<int>("ImpactoPedra")
                        .HasColumnType("integer");

                    b.Property<int>("ImpactoPoderMilitar")
                        .HasColumnType("integer");

                    b.Property<int>("ImpactoPopulacao")
                        .HasColumnType("integer");

                    b.Property<int>("ImpactoTecnologia")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("EventosCivilizacionais");
                });

            modelBuilder.Entity("CORE.Domain.Entities.Civilizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Comida")
                        .HasColumnType("integer");

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Madeira")
                        .HasColumnType("integer");

                    b.Property<int>("Moral")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Pedra")
                        .HasColumnType("integer");

                    b.Property<int>("PoderMilitar")
                        .HasColumnType("integer");

                    b.Property<int>("Populacao")
                        .HasColumnType("integer");

                    b.Property<int>("Tecnologia")
                        .HasColumnType("integer");

                    b.Property<int>("Territorios")
                        .HasColumnType("integer");

                    b.Property<int>("Turno")
                        .HasColumnType("integer");

                    b.Property<int>("UltimoEvento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Civilizacoes");
                });

            modelBuilder.Entity("CORE.Domain.Entities.Regiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CivilizacaoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Controlada")
                        .HasColumnType("boolean");

                    b.Property<int>("NivelDesenvolvimento")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("ProducaoComida")
                        .HasColumnType("integer");

                    b.Property<int>("ProducaoMadeira")
                        .HasColumnType("integer");

                    b.Property<int>("ProducaoPedra")
                        .HasColumnType("integer");

                    b.Property<string>("Terreno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regioes");
                });
#pragma warning restore 612, 618
        }
    }
}
